#!/bin/bash
# =============================================================================
# Inject Secrets to Raspberry Pi
# =============================================================================
# This script injects secrets from local environment variables (loaded via
# 1Password) to the Raspberry Pi's configuration file.
#
# This is called automatically by deploy_to_pi.sh, but can be run standalone.
#
# Usage:
#   source scripts/load_secrets.sh
#   ./scripts/inject_secrets.sh
#
# The script creates /etc/payphone/.env on the Raspberry Pi with all secrets
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}Injecting secrets to Raspberry Pi...${NC}"

# -----------------------------------------------------------------------------
# Check required environment variables
# -----------------------------------------------------------------------------

if [ -z "$PI_HOST" ] || [ -z "$PI_USER" ]; then
    echo -e "${RED}ERROR: PI_HOST and PI_USER must be set${NC}"
    echo "Load secrets first: source scripts/load_secrets.sh"
    exit 1
fi

# -----------------------------------------------------------------------------
# Build SSH command
# -----------------------------------------------------------------------------

SSH_OPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR"

if [ -n "$PI_SSH_KEY_PATH" ] && [ -f "$PI_SSH_KEY_PATH" ]; then
    SSH_CMD="ssh -i $PI_SSH_KEY_PATH $SSH_OPTS -p ${PI_PORT:-22} ${PI_USER}@${PI_HOST}"
    SCP_CMD="scp -i $PI_SSH_KEY_PATH $SSH_OPTS -P ${PI_PORT:-22}"
elif [ -n "$PI_PASSWORD" ]; then
    # Use sshpass if available
    if command -v sshpass &> /dev/null; then
        SSH_CMD="sshpass -p '$PI_PASSWORD' ssh $SSH_OPTS -p ${PI_PORT:-22} ${PI_USER}@${PI_HOST}"
        SCP_CMD="sshpass -p '$PI_PASSWORD' scp $SSH_OPTS -P ${PI_PORT:-22}"
    else
        echo -e "${YELLOW}WARNING: sshpass not installed, will prompt for password${NC}"
        SSH_CMD="ssh $SSH_OPTS -p ${PI_PORT:-22} ${PI_USER}@${PI_HOST}"
        SCP_CMD="scp $SSH_OPTS -P ${PI_PORT:-22}"
    fi
else
    SSH_CMD="ssh $SSH_OPTS -p ${PI_PORT:-22} ${PI_USER}@${PI_HOST}"
    SCP_CMD="scp $SSH_OPTS -P ${PI_PORT:-22}"
fi

# -----------------------------------------------------------------------------
# Test connection
# -----------------------------------------------------------------------------

echo "Testing connection to ${PI_USER}@${PI_HOST}..."

if ! $SSH_CMD "echo 'Connection successful'" &>/dev/null; then
    echo -e "${RED}ERROR: Cannot connect to Raspberry Pi${NC}"
    echo "Check your credentials and network connection"
    exit 1
fi

echo -e "${GREEN}✓ Connected to Raspberry Pi${NC}"

# -----------------------------------------------------------------------------
# Create environment file content
# -----------------------------------------------------------------------------

echo "Building environment configuration..."

ENV_CONTENT=$(cat <<'EOF'
# =============================================================================
# Payphone Configuration
# =============================================================================
# This file is automatically generated by inject_secrets.sh
# DO NOT EDIT MANUALLY - changes will be overwritten on next deployment
# =============================================================================

# Hardware Configuration
USE_GPIO=true
SERIAL_PORT=/dev/ttyUSB0
BAUDRATE=9600
KEYPAD_ROW_PINS=[5, 6, 13, 19]
KEYPAD_COL_PINS=[26, 20, 21]
HOOK_SWITCH_PIN=17

# Audio Configuration
AUDIO_DIR=/home/pi/payphone/audio_files
SAMPLE_RATE=44100

# Menu Configuration
MENU_TIMEOUT=30

# Feature Flags
ENABLE_RECORDING=false
ENABLE_CELLULAR=false

# Development & Debugging
DEBUG=false
LOG_LEVEL=INFO
LOG_FILE=/var/log/payphone/payphone.log
EOF
)

# Add API keys if they exist
if [ -n "$OPENAI_API_KEY" ]; then
    ENV_CONTENT+=$'\n\n# OpenAI API'
    ENV_CONTENT+=$'\nOPENAI_API_KEY='"$OPENAI_API_KEY"
fi

if [ -n "$TWILIO_ACCOUNT_SID" ]; then
    ENV_CONTENT+=$'\n\n# Twilio API'
    ENV_CONTENT+=$'\nTWILIO_ACCOUNT_SID='"$TWILIO_ACCOUNT_SID"
    ENV_CONTENT+=$'\nTWILIO_AUTH_TOKEN='"$TWILIO_AUTH_TOKEN"
    ENV_CONTENT+=$'\nTWILIO_PHONE_NUMBER='"$TWILIO_PHONE_NUMBER"
fi

if [ -n "$WEATHER_API_KEY" ]; then
    ENV_CONTENT+=$'\n\n# Weather API'
    ENV_CONTENT+=$'\nWEATHER_API_KEY='"$WEATHER_API_KEY"
fi

# -----------------------------------------------------------------------------
# Upload environment file to Raspberry Pi
# -----------------------------------------------------------------------------

echo "Creating configuration directory on Pi..."

$SSH_CMD "sudo mkdir -p /etc/payphone && sudo chown ${PI_USER}:${PI_USER} /etc/payphone"

echo "Uploading environment configuration..."

# Create temp file
TEMP_ENV_FILE=$(mktemp)
echo "$ENV_CONTENT" > "$TEMP_ENV_FILE"

# Upload to Pi
$SCP_CMD "$TEMP_ENV_FILE" "${PI_USER}@${PI_HOST}:/etc/payphone/.env"

# Secure the file (readable only by owner and root)
$SSH_CMD "chmod 600 /etc/payphone/.env"

# Cleanup temp file
rm "$TEMP_ENV_FILE"

echo -e "${GREEN}✓ Configuration uploaded${NC}"

# -----------------------------------------------------------------------------
# Verify installation
# -----------------------------------------------------------------------------

echo "Verifying configuration..."

if $SSH_CMD "[ -f /etc/payphone/.env ]"; then
    FILE_SIZE=$($SSH_CMD "wc -c < /etc/payphone/.env")
    echo -e "${GREEN}✓ Configuration file exists (${FILE_SIZE} bytes)${NC}"
else
    echo -e "${RED}ERROR: Configuration file not created${NC}"
    exit 1
fi

# -----------------------------------------------------------------------------
# Update systemd service to use environment file
# -----------------------------------------------------------------------------

echo "Configuring systemd service..."

$SSH_CMD "sudo mkdir -p /etc/systemd/system/payphone.service.d"

$SSH_CMD "sudo tee /etc/systemd/system/payphone.service.d/override.conf > /dev/null" <<'SYSTEMD_OVERRIDE'
[Service]
EnvironmentFile=/etc/payphone/.env
SYSTEMD_OVERRIDE

$SSH_CMD "sudo systemctl daemon-reload"

echo -e "${GREEN}✓ Systemd service configured${NC}"

# -----------------------------------------------------------------------------
# Summary
# -----------------------------------------------------------------------------

echo ""
echo -e "${GREEN}================================================${NC}"
echo -e "${GREEN}Secrets injected successfully!${NC}"
echo -e "${GREEN}================================================${NC}"
echo ""
echo "Configuration file: /etc/payphone/.env"
echo "File permissions: 600 (owner read/write only)"
echo "Systemd service: configured to load environment"
echo ""
echo "Injected secrets:"
echo "  - Hardware configuration"
echo "  - Audio configuration"
echo "  - Menu settings"
[ -n "$OPENAI_API_KEY" ] && echo "  - OpenAI API key"
[ -n "$TWILIO_ACCOUNT_SID" ] && echo "  - Twilio API credentials"
[ -n "$WEATHER_API_KEY" ] && echo "  - Weather API key"
echo ""
echo "The payphone service will use these settings on next start."
echo "Restart the service: ssh ${PI_USER}@${PI_HOST} 'sudo systemctl restart payphone'"
echo ""
